# Generated by Django 2.2.19 on 2022-12-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221221_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/%Y/%m/%d')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='catalog.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsImage',
        ),
    ]
