# Generated by Django 2.2.19 on 2022-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20221221_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(help_text='Введите стоимость книги', null=True, verbose_name='стоимость книги'),
        ),
    ]
