# Generated by Django 2.2.19 on 2022-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=0, help_text='загрузите картинку книги', upload_to='', verbose_name='фото книги'),
        ),
        migrations.DeleteModel(
            name='BooksImage',
        ),
    ]
