# Generated by Django 4.1.4 on 2022-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221222_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.BooleanField(default=0, help_text='Твердый - 1. Мягкий - 0.', verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='book',
            name='height',
            field=models.IntegerField(help_text='Введите высоту книги в см', null=True, verbose_name='Высота книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(help_text='Введите количество страниц книги', null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='ves',
            field=models.IntegerField(help_text='Введите вес книги в граммах', null=True, verbose_name='вес книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='width',
            field=models.IntegerField(help_text='Введите ширину книги в см', null=True, verbose_name='Ширина книги'),
        ),
    ]
